### PR TITLE
Extracts source repo from wiki and generates model out of it

### PR DESCRIPTION
**Pull request by ipa-hsd**

### CODE REVIEW

**Comment by ipa-hsd** [comment]
generated models are in https://github.com/ipa320/RosCommonModels/pull/9

**Comment by ipa-hsd** [comment]
FYI @ipa-nhg

**Comment by ipa-nhg** [comment]
@ipa-hsd is this PR still WIP or ready for review?

**Comment by ipa-hsd** [comment]
Still a WIP, will push the remaining changes now. But not sure if it makes sense to merge because looking at the source of the wiki pages, they are not standard. So had to use hot-fixes at times. Will ping when it is "ready"

**Review by ipa-nhg — APPROVED** [review]
I don't have time for testing locally but as they are all new scripts (it can't crash previous code) and you pushed the results you obtained to other repo and are pretty good, I will merge!

Thanks @ipa-hsd 👍🏽

**Pull request merged**
